name: Build and Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.80.0
      - name: Build
        # I always allow dead_code in test runs.
        run: RUSTFLAGS="$RUSTFLAGS -A dead_code" cargo build --verbose
      - name: Test
        run: cargo test --verbose

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.80.0
      - name: Lint
      - name: Test
        run: cargo clippy
